trigger:
  batch: true
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:
  - stage: Core Tests
    dependsOn: []
    jobs:
      - job: network-build-test
        pool:
          vmImage: 'macos-latest'
        timeoutInMinutes: 5
        steps:
          - script: dotnet tool restore
            displayName: 'DotNet Restore'
          - script: dotnet cake --target=network-build --configuration=release
            displayName: 'Network Build' 
          - script: dotnet cake --target=network-test --configuration=release
            displayName: 'Network Test'
          - task: PublishTestResults@2
            continueOnError: true
            inputs:
              testResultsFormat: 'VSTest'
              testResultsFiles: 'Artifacts/*.trx'
              failTaskOnFailedTests: true
          - publish: '$(System.ArtifactStagingDirectory)/Artifacts'
            displayName: 'Publish Artifacts'
            artifact: Artifacts


  - stage: Core Publish
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/core_')
    dependsOn: 'Core Tests'
    jobs:
      - job: network-build-publish
        pool:
          vmImage: 'macos-latest'
        timeoutInMinutes: 5
        variables:
          - name : tagName
            value: $[ replace(variables['Build.SourceBranch'], 'refs/tags/core_', '') ] 
          - group: Tokens
        steps:
          - download: current
            displayName: 'Download Artifacts'
            artifact: Artifacts
          - script: dotnet tool restore
            displayName: 'DotNet Restore'
          - script: dotnet cake --target=network-publish --apikey=$(NUGET_API_KEY)
            displayName: 'Network Publish'
            
