trigger:
  batch: true
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:
  - stage: CoreTests
    dependsOn: []
    jobs:
      - job: Build
        pool:
          vmImage: 'macos-latest'
        timeoutInMinutes: 5
        variables:
          - name : version
            ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/core_') }}:
              value: $[ replace(variables['Build.SourceBranch'], 'refs/tags/core_', '') ] 
            ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/tags/core_')) }}:
              value: '1.0'
          - group: Tokens
        steps:
          - script: curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -Channel 7.0.1xx -Quality preview
            displayName: 'Install .NET 7.0.1xx Preview'
          - script: dotnet tool restore
            displayName: 'DotNet Restore'
          - script: dotnet cake --target=network-build --configuration=release --up-version=$(version)
            displayName: 'Network Build' 
          - script: dotnet cake --target=network-test --configuration=release
            displayName: 'Network Test'
          - task: PublishTestResults@2
            continueOnError: true
            inputs:
              testResultsFormat: 'VSTest'
              testResultsFiles: 'Artifacts/*.trx'
              failTaskOnFailedTests: true
          - publish: 'Artifacts/Common'
            displayName: 'Publish Artifacts'
            artifact: Artifacts


  - stage: CorePublish
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/core_')
    dependsOn: CoreTests
    jobs:
      - job: Publish
        pool:
          vmImage: 'macos-latest'
        timeoutInMinutes: 5
        steps:
          - download: current
            displayName: 'Download Artifacts'
            artifact: Artifacts
          - script: dotnet tool restore
            displayName: 'DotNet Restore'
          - script: dotnet cake --target=network-publish --apikey=$(NUGET_API_KEY)
            displayName: 'Network Publish'
            
