trigger:
  batch: true
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'


stages:
  - stage: CoreTests
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags'))
    dependsOn: []
    jobs:
      - job: Build
        pool:
          vmImage: 'macos-latest'
        timeoutInMinutes: 5
        steps:
          - script: curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -Channel 7.0.1xx -Quality preview
            displayName: 'Install .NET 7.0.1xx Preview'
          - script: dotnet tool restore
            displayName: 'DotNet Restore'
          - script: dotnet cake --target=network-test --configuration=release
            displayName: 'Network Test'
          - task: PublishTestResults@2
            continueOnError: true
            inputs:
              testResultsFormat: 'VSTest'
              testResultsFiles: 'Artifacts/*.trx'
              failTaskOnFailedTests: true


  - stage: Publish
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/cappuccino_')
    dependsOn: []
    jobs:
      - job: Build
        pool:
          vmImage: 'macos-latest'
        timeoutInMinutes: 15
        variables:
          - name : version
            value: $[ replace(variables['Build.SourceBranch'], 'refs/tags/cappuccino_', '') ] 
          - group: Tokens
        steps:
#//////////////////////////////////////////////////////////////////////
#// Prepare
#//////////////////////////////////////////////////////////////////////
          - task: InstallAppleCertificate@2
            displayName: 'Install Apple certificate'
            inputs:
              certSecureFile: 'certificate.p12'
              certPwd: '$(PROVISION_KEY)'
          - task: InstallAppleProvisioningProfile@1
            displayName: 'Install Apple provisioning profile'
            inputs:
              provProfileSecureFile: 'profile.mobileprovision'
          - task: DownloadSecureFile@1
            name: strongKey
            displayName: 'Download Strong Key'
            inputs:
              secureFile: 'key.snk'
          - script: curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -Channel 7.0.1xx -Quality preview
            displayName: 'Install .NET 7.0.1xx Preview'
          - script: dotnet workload install ios
            displayName: 'Install Workloads'
          - script: dotnet tool restore
            displayName: 'DotNet Restore'
#//////////////////////////////////////////////////////////////////////
#// Build
#//////////////////////////////////////////////////////////////////////
          - script: dotnet cake --up-version=$(version) --sign-key=$(strongKey.secureFilePath)
            displayName: 'Build All'
          - publish: 'Artifacts'
            displayName: 'Publish Artifacts'
            artifact: Artifacts

